Updated protocol version to 180004,
BTCPrivate/BitcoinPrivate-seeder pull request #2
Opened 2018-04-14 13:44 UTC by donshin

Updated the checks to accept new IP address requests from nodes down to protocol version 180003 but only report 180004 nodes.

2018-04-14 18:35 UTC, djenriquez requested changes
Maybe we could help get rid of some of the magic numbers.

2018-04-14 18:35 UTC, djenriquez commented on db.h
> +    if (clientVersion && clientVersion < 180003) { return 604800; }
Does it make sense to define this as a variable up top? I believe that would help maintenance in the future.

2018-04-14 20:31 UTC, ch4ot1c commented
lgtm

2018-04-18 07:04 UTC, djenriquez approved these changes
🎉

2018-04-18 21:58 UTC, merged